const {useState} = React;
const monthlySample = [
  {month:'本月', tokens:'10 亿 2 千万', cost:'$1,428.36', ratio:100, current:true},
  {month:'8 月', tokens:'3 亿 8 千万', cost:'$1,068.20', ratio:37.25},
  {month:'7 月', tokens:'2 亿', cost:'$876.50', ratio:19.61},
  {month:'6 月', tokens:'1 亿', cost:'$640.25', ratio:9.80},
  {month:'5 月', tokens:'6 千万', cost:'$492.65', ratio:5.88},
  {month:'4 月', tokens:'2 千万', cost:'$379.00', ratio:1.96},
];
function MonthlyHeading(){return <div className="variant-heading"><h2><span className="calendar-icon" aria-hidden="true"></span>月度统计</h2><span className="period">近 6 个月</span></div>;}
function Footnote({children='本月统计截至当前时刻'}){return <div className="variant-footnote"><span className="tiny-info">i</span><span>{children}</span></div>;}
function MonthTile({month,tokens,cost,current=false}){return <div className={'month-tile'+(current?' current':'')}><div className="tile-title">{current&&<i className="tile-dot"></i>}{month}</div><div className="tile-number">{tokens}<small>Token</small></div><div className="tile-cost"><span>API 费用</span><strong>{cost}</strong></div></div>;}
function TileVariant(){return <div className="variant-frame" data-screen-label="A · 月份卡片"><section className="variant-card"><MonthlyHeading/><div className="month-tiles"><MonthTile month="本月" tokens="10 亿 2 千万" cost="$1,428.36" current/><MonthTile month="8 月" tokens="3 亿 8 千万" cost="$1,068.20"/><MonthTile month="7 月" tokens="2 亿" cost="$876.50"/><MonthTile month="6 月" tokens="1 亿" cost="$640.25"/><MonthTile month="5 月" tokens="6 千万" cost="$492.65"/><MonthTile month="4 月" tokens="2 千万" cost="$379.00"/></div><Footnote/></section><div className="variant-caption"><strong>A · 月份卡片</strong><p>每个月一张小卡片，Token 与费用成组展示。</p></div></div>;}
function BarMonth({month,tokens,cost,ratio,current=false}){return <div className={'bar-month'+(current?' current':'')}><div className="bar-month-label">{month}</div><div><div className="bar-metrics"><div><strong>{tokens}</strong><span>Token</span></div><div><strong>{cost}</strong><span>API 等效费用</span></div></div><div className="usage-bar-track" aria-label={`${month} Token 为本月的 ${ratio}%`}><i className="usage-bar-fill" style={{width:ratio+'%'}}></i></div></div></div>;}
function BarsVariant(){return <div className="variant-frame" data-screen-label="B · 横向用量条"><section className="variant-card"><MonthlyHeading/><div className="bar-months"><BarMonth month="本月" tokens="10 亿 2 千万" cost="$1,428.36" ratio={100} current/><BarMonth month="8 月" tokens="3 亿 8 千万" cost="$1,068.20" ratio={37.25}/><BarMonth month="7 月" tokens="2 亿" cost="$876.50" ratio={19.61}/><BarMonth month="6 月" tokens="1 亿" cost="$640.25" ratio={9.8}/><BarMonth month="5 月" tokens="6 千万" cost="$492.65" ratio={5.88}/><BarMonth month="4 月" tokens="2 千万" cost="$379.00" ratio={1.96}/></div><Footnote>横条表示 Token 用量，费用单独列出</Footnote></section><div className="variant-caption"><strong>B · 横向用量条</strong><p>数字保持左对齐，月份之间的用量差异更直观。</p></div></div>;}
function SwitchVariant(){const [selected,setSelected]=useState(0);const month=monthlySample[selected];return <div className="variant-frame" data-screen-label="C · 按月切换"><section className="variant-card month-selector-card"><MonthlyHeading/><div className="month-tabs" role="group" aria-label="选择月份">{monthlySample.map((item,index)=><button key={item.month} className={'month-tab'+(index===selected?' active':'')} aria-pressed={index===selected} onClick={()=>setSelected(index)}>{item.month}</button>)}</div><div className="month-detail-title"><span className="month-status-dot"></span>{month.month}用量</div><div className="selected-metrics"><div className="selected-metric"><span>Token</span><strong>{month.tokens}</strong></div><div className="selected-metric"><span>API 等效费用</span><strong>{month.cost}</strong></div></div><div className="mini-month-bars" aria-label="各月 Token 用量">{monthlySample.map((item,index)=><button key={item.month} className={'mini-month-bar'+(index===selected?' selected':'')} onClick={()=>setSelected(index)} aria-label={`查看${item.month}用量`} title={`${item.month} · ${item.tokens} Token`}><i style={{height:Math.max(item.ratio,8)+'%'}}></i></button>)}</div><Footnote>{selected===0?'本月统计截至当前时刻':`${month.month}统计已完成`}</Footnote></section><div className="variant-caption"><strong>C · 按月切换</strong><p>点击月份查看双指标，最省主面板空间。</p></div></div>;}
function MonthlyStyleApp(){
  const [dark,setDark]=useState(false);
  const style=new URLSearchParams(location.search).get('style');
  React.useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
  const variants={a:TileVariant,b:BarsVariant,c:SwitchVariant};
  const Selected=variants[style];
  return <><header className="styles-toolbar"><span className="styles-title">月度统计 · 样式对比</span><div className="styles-actions"><a href="Monthly%20Usage%20Styles.html" aria-current={!Selected?'page':undefined}>对比</a><a href="?style=a" aria-current={style==='a'?'page':undefined}>A</a><a href="?style=b" aria-current={style==='b'?'page':undefined}>B</a><a href="?style=c" aria-current={style==='c'?'page':undefined}>C</a><button onClick={()=>setDark(!dark)}>{dark?'浅色':'深色'}</button></div></header>{Selected?<div className="standalone-variant"><div className="standalone-label"><span>Codex Meter · 月度统计</span><span>示例数据</span></div><Selected/><div className="style-preview-controls"><span>保留显隐、3 / 6 / 12 个月与排序配置</span></div></div>:<div className="canvas-wrapper"><DesignCanvas style={{height:'100%'}}><DCSection id="monthly-style-options" title="让每个月的用量更好读" subtitle="同一份数据，三种呈现方式。点击 A / B / C 查看原尺寸。"><DCArtboard id="monthly-tiles" label="A · 月份卡片（推荐）" width={420} height={510}><TileVariant/></DCArtboard><DCArtboard id="monthly-bars" label="B · 横向用量条" width={420} height={560}><BarsVariant/></DCArtboard><DCArtboard id="monthly-switch" label="C · 按月切换" width={420} height={450}><SwitchVariant/></DCArtboard></DCSection></DesignCanvas></div>}</>;
}
ReactDOM.createRoot(document.getElementById('styles-root')).render(<MonthlyStyleApp/>);
